// Mock data untuk Resource Finder

export const userData = {
    id: 'STD-2024001',
    name: 'Ahmad Rizky',
    nim: '2024001',
    major: 'Desain Komunikasi Visual',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahmad',
    interests: ['Editing', 'Photography', 'Graphic Design'],
};

export const todaySchedule = [
    {
        id: 1,
        subject: 'Desain Grafis',
        room: 'D-301',
        building: 'Gedung D',
        startTime: '08:00',
        endTime: '10:30',
        lecturer: 'Drs. Budi Santoso',
    },
    {
        id: 2,
        subject: 'Fotografi Dasar',
        room: 'Studio 1',
        building: 'Gedung C',
        startTime: '13:00',
        endTime: '15:30',
        lecturer: 'Ratna Dewi, M.Sn',
    },
    {
        id: 3,
        subject: 'Animasi 2D',
        room: 'Lab Komputer A',
        building: 'Gedung D',
        startTime: '16:00',
        endTime: '18:00',
        lecturer: 'Dr. Andi Wijaya',
    },
];

export const freeTimeSlots = [
    {
        id: 1,
        afterClass: 'Desain Grafis',
        startTime: '10:30',
        endTime: '13:00',
        duration: '2 Jam 30 Menit',
        location: 'Gedung D',
    },
];

export const facilities = [
    {
        id: 1,
        name: 'Lab Komputer A',
        type: 'computer-lab',
        building: 'Gedung D',
        floor: 'Lantai 2',
        distance: 50,
        status: 'available',
        lastServiced: '2024-12-15',
        capacity: 30,
        available: 12,
        rows: 5,
        cols: 6,
        specs: ['Intel i7', 'RTX 3060', 'Dual Monitor'],
        software: ['Adobe CC 2024', 'AutoCAD', 'Blender'],
        rules: [
            'Maksimal 2 jam per sesi',
            'Dilarang makan dan minum',
            'Wajib logout setelah selesai',
        ],
        image: 'https://images.unsplash.com/photo-1568702846914-96b305d2ead1?w=400',
        computers: [
            { id: 'PC-01', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 156, totalHours: 234, lastUsedBy: 'Indra Wijaya' },
            { id: 'PC-02', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 142, totalHours: 198, lastUsedBy: 'Siti Aminah' },
            { id: 'PC-03', status: 'occupied', specs: 'Intel i7, RTX 3060', occupiedBy: 'Ahmad Rizky', until: '12:00', usageCount: 189, totalHours: 312, lastUsedBy: 'Ahmad Rizky' },
            { id: 'PC-04', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 98, totalHours: 145, lastUsedBy: 'Joko Susilo' },
            { id: 'PC-05', status: 'maintenance', specs: 'Intel i7, RTX 3060', usageCount: 201, totalHours: 356, lastUsedBy: 'Rina Marlina' },
            { id: 'PC-06', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 87, totalHours: 124, lastUsedBy: 'Dewi Lestari' },
            { id: 'PC-07', status: 'occupied', specs: 'Intel i7, RTX 3060', occupiedBy: 'Budi Santoso', until: '11:30', usageCount: 167, totalHours: 278, lastUsedBy: 'Budi Santoso' },
            { id: 'PC-08', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 112, totalHours: 167, lastUsedBy: 'Maya Sari' },
            { id: 'PC-09', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 134, totalHours: 189, lastUsedBy: 'Andi Pratama' },
            { id: 'PC-10', status: 'occupied', specs: 'Intel i7, RTX 3060', occupiedBy: 'Citra Dewi', until: '13:00', usageCount: 178, totalHours: 298, lastUsedBy: 'Citra Dewi' },
            { id: 'PC-11', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 92, totalHours: 138, lastUsedBy: 'Rudi Hartono' },
            { id: 'PC-12', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 76, totalHours: 112, lastUsedBy: 'Lina Kusuma' },
            { id: 'PC-13', status: 'maintenance', specs: 'Intel i7, RTX 3060', usageCount: 198, totalHours: 345, lastUsedBy: 'Bambang Surya' },
            { id: 'PC-14', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 85, totalHours: 128, lastUsedBy: 'Nita Anggraini' },
            { id: 'PC-15', status: 'occupied', specs: 'Intel i7, RTX 3060', occupiedBy: 'Diana Putri', until: '14:00', usageCount: 156, totalHours: 234, lastUsedBy: 'Diana Putri' },
            { id: 'PC-16', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 104, totalHours: 156, lastUsedBy: 'Tommy Setiawan' },
            { id: 'PC-17', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 118, totalHours: 178, lastUsedBy: 'Yuni Astuti' },
            { id: 'PC-18', status: 'occupied', specs: 'Intel i7, RTX 3060', occupiedBy: 'Eko Prasetyo', until: '11:00', usageCount: 145, totalHours: 212, lastUsedBy: 'Eko Prasetyo' },
            { id: 'PC-19', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 67, totalHours: 98, lastUsedBy: 'Rina Wati' },
            { id: 'PC-20', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 89, totalHours: 132, lastUsedBy: 'Agus Setiawan' },
            { id: 'PC-21', status: 'occupied', specs: 'Intel i7, RTX 3060', occupiedBy: 'Fani Ayu', until: '12:30', usageCount: 134, totalHours: 198, lastUsedBy: 'Fani Ayu' },
            { id: 'PC-22', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 78, totalHours: 115, lastUsedBy: 'Doni Kurniawan' },
            { id: 'PC-23', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 95, totalHours: 142, lastUsedBy: 'Sinta Dewi' },
            { id: 'PC-24', status: 'maintenance', specs: 'Intel i7, RTX 3060', usageCount: 187, totalHours: 324, lastUsedBy: 'Wahyu Nugroho' },
            { id: 'PC-25', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 108, totalHours: 162, lastUsedBy: 'Lisa Permata' },
            { id: 'PC-26', status: 'occupied', specs: 'Intel i7, RTX 3060', occupiedBy: 'Gunawan', until: '15:00', usageCount: 156, totalHours: 234, lastUsedBy: 'Gunawan' },
            { id: 'PC-27', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 72, totalHours: 108, lastUsedBy: 'Ratna Sari' },
            { id: 'PC-28', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 83, totalHours: 124, lastUsedBy: 'Hendra Putra' },
            { id: 'PC-29', status: 'available', specs: 'Intel i7, RTX 3060', usageCount: 91, totalHours: 136, lastUsedBy: 'Ani Susanti' },
            { id: 'PC-30', status: 'occupied', specs: 'Intel i7, RTX 3060', occupiedBy: 'Hana', until: '13:30', usageCount: 145, totalHours: 218, lastUsedBy: 'Hana' },
        ],
    },
    {
        id: 2,
        name: 'Studio Foto 1',
        type: 'studio',
        building: 'Gedung C',
        floor: 'Lantai 1',
        distance: 120,
        status: 'available',
        lastServiced: '2024-12-10',
        capacity: 5,
        available: 2,
        specs: ['Backdrop 3x4m', 'Softbox', 'Ring Light'],
        software: [],
        equipment: ['Canon 5D Mark IV', 'Tripod Pro', 'Flash External'],
        rules: [
            'Wajib menggunakan sandal studio',
            'Kembalikan peralatan ke tempat semula',
            'Maksimal 3 jam per sesi',
        ],
        image: 'https://images.unsplash.com/photo-1574717025058-2f8737d2e2b7?w=400',
    },
    {
        id: 3,
        name: 'Editing Room B',
        type: 'editing',
        building: 'Gedung D',
        floor: 'Lantai 3',
        distance: 80,
        status: 'limited',
        lastServiced: '2024-12-08',
        capacity: 10,
        available: 2,
        specs: ['iMac 27"', 'Color Calibrated', 'Audio Interface'],
        software: ['DaVinci Resolve', 'Premiere Pro', 'After Effects'],
        rules: [
            'Prioritas untuk mahasiswa semester akhir',
            'Dilarang menginstall software tanpa izin',
        ],
        image: 'https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=400',
    },
    {
        id: 4,
        name: 'Sound Lab',
        type: 'studio',
        building: 'Gedung C',
        floor: 'Basement',
        distance: 200,
        status: 'full',
        lastServiced: '2024-12-05',
        capacity: 4,
        available: 0,
        specs: ['Soundproof', 'Mixing Console', 'Studio Monitor'],
        software: ['Pro Tools', 'Ableton Live', 'Logic Pro'],
        equipment: ['Condenser Mic', 'Pop Filter', 'MIDI Keyboard'],
        rules: [
            'Booking minimal H-1',
            'Wajib menggunakan headphone',
        ],
        image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400',
    },
    {
        id: 5,
        name: 'Library PC Zone',
        type: 'computer-lab',
        building: 'Perpustakaan',
        floor: 'Lantai 2',
        distance: 300,
        status: 'available',
        capacity: 20,
        available: 15,
        specs: ['Intel i5', 'Basic Monitor'],
        software: ['Microsoft Office', 'SPSS', 'EndNote'],
        rules: [
            'Area tenang - harap jaga keheningan',
            'Maksimal 1 jam jika ada antrian',
        ],
        image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400',
    },
    {
        id: 6,
        name: 'Meeting Room 1',
        type: 'meeting',
        building: 'Gedung A',
        floor: 'Lantai 3',
        distance: 150,
        status: 'maintenance',
        capacity: 12,
        available: 0,
        specs: ['Projector', 'Whiteboard', 'Video Conference'],
        software: [],
        rules: [
            'Untuk diskusi kelompok min. 4 orang',
            'Booking melalui admin gedung',
        ],
        image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400',
    },
];

export const bookings = [
    {
        id: 'BK-001',
        facilityId: 1,
        facilityName: 'Lab Komputer A',
        building: 'Gedung D',
        floor: 'Lantai 2',
        date: '2024-12-18',
        startTime: '10:30',
        endTime: '12:00',
        status: 'active',
        pcNumber: 'PC-05',
        qrCode: 'RF-BK001-2024',
    },
    {
        id: 'BK-002',
        facilityId: 2,
        facilityName: 'Studio Foto 1',
        building: 'Gedung C',
        floor: 'Lantai 1',
        date: '2024-12-19',
        startTime: '14:00',
        endTime: '16:00',
        status: 'upcoming',
        qrCode: 'RF-BK002-2024',
    },
];

export const bookingHistory = [
    {
        id: 'BK-H001',
        facilityName: 'Editing Room B',
        date: '2024-12-15',
        startTime: '09:00',
        endTime: '11:00',
        status: 'completed',
    },
    {
        id: 'BK-H002',
        facilityName: 'Lab Komputer A',
        date: '2024-12-14',
        startTime: '13:00',
        endTime: '15:00',
        status: 'completed',
    },
    {
        id: 'BK-H003',
        facilityName: 'Sound Lab',
        date: '2024-12-12',
        startTime: '10:00',
        endTime: '12:00',
        status: 'cancelled',
    },
];

export const notifications = [
    {
        id: 1,
        type: 'reminder',
        title: 'Booking akan dimulai',
        message: 'Lab Komputer A dalam 15 menit lagi. Jangan lupa check-in!',
        time: '5 menit lalu',
        read: false,
    },
    {
        id: 2,
        type: 'recommendation',
        title: 'Waktu kosong terdeteksi',
        message: 'Kamu punya 2 jam kosong. Studio Foto 1 tersedia!',
        time: '30 menit lalu',
        read: false,
    },
    {
        id: 3,
        type: 'update',
        title: 'Laporan ditangani',
        message: 'Mouse rusak di PC-05 sudah diganti. Terima kasih!',
        time: '2 jam lalu',
        read: true,
    },
];

export const timeSlots = [
    { time: '08:00', status: 'class', classInfo: 'Desain Grafis' },
    { time: '09:00', status: 'class', classInfo: 'Desain Grafis' },
    { time: '10:00', status: 'class', classInfo: 'Desain Grafis' },
    { time: '11:00', status: 'available' },
    { time: '12:00', status: 'available' },
    { time: '13:00', status: 'class', classInfo: 'Fotografi Dasar' },
    { time: '14:00', status: 'class', classInfo: 'Fotografi Dasar' },
    { time: '15:00', status: 'class', classInfo: 'Fotografi Dasar' },
    { time: '16:00', status: 'class', classInfo: 'Animasi 2D' },
    { time: '17:00', status: 'class', classInfo: 'Animasi 2D' },
    { time: '18:00', status: 'available' },
    { time: '19:00', status: 'limited' },
    { time: '20:00', status: 'full' },
];

export const categories = [
    { id: 'all', name: 'Semua', icon: '🏢' },
    { id: 'computer-lab', name: 'Lab Komputer', icon: '💻' },
    { id: 'studio', name: 'Studio', icon: '📸' },
    { id: 'editing', name: 'Editing', icon: '🎬' },
    { id: 'meeting', name: 'Meeting Room', icon: '👥' },
];

// Peak hours data for facility density visualization
export const peakHoursData = [
    { time: '08:00 - 10:00', level: 'high', percentage: 85, label: 'Ramai 🔥' },
    { time: '10:00 - 12:00', level: 'medium', percentage: 65, label: 'Sedang' },
    { time: '12:00 - 14:00', level: 'low', percentage: 35, label: 'Sepi' },
    { time: '14:00 - 16:00', level: 'high', percentage: 90, label: 'Ramai 🔥' },
    { time: '16:00 - 18:00', level: 'medium', percentage: 55, label: 'Sedang' },
    { time: '18:00 - 20:00', level: 'low', percentage: 25, label: 'Sepi' },
];

// Activity logs for tracking user actions
export const activityLogs = [
    {
        id: 1,
        userId: 'STD-2024001',
        userName: 'Ahmad Rizky',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahmad',
        action: 'check-in',
        facility: 'Lab Komputer A',
        facilityId: 1,
        pcNumber: 'PC-03',
        timestamp: '2024-12-23T10:30:00',
        duration: null,
    },
    {
        id: 2,
        userId: 'STD-2024002',
        userName: 'Budi Santoso',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=budi',
        action: 'check-in',
        facility: 'Lab Komputer A',
        facilityId: 1,
        pcNumber: 'PC-07',
        timestamp: '2024-12-23T09:00:00',
        duration: null,
    },
    {
        id: 3,
        userId: 'STD-2024003',
        userName: 'Citra Dewi',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=citra',
        action: 'check-out',
        facility: 'Editing Room B',
        facilityId: 3,
        pcNumber: 'PC-02',
        timestamp: '2024-12-23T11:45:00',
        duration: '2h 30m',
    },
    {
        id: 4,
        userId: 'STD-2024001',
        userName: 'Ahmad Rizky',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahmad',
        action: 'booking',
        facility: 'Studio Foto 1',
        facilityId: 2,
        pcNumber: null,
        timestamp: '2024-12-22T14:00:00',
        duration: '2h',
    },
    {
        id: 5,
        userId: 'STD-2024004',
        userName: 'Diana Putri',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=diana',
        action: 'check-in',
        facility: 'Lab Komputer A',
        facilityId: 1,
        pcNumber: 'PC-15',
        timestamp: '2024-12-23T12:00:00',
        duration: null,
    },
    {
        id: 6,
        userId: 'STD-2024001',
        userName: 'Ahmad Rizky',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahmad',
        action: 'check-out',
        facility: 'Lab Komputer A',
        facilityId: 1,
        pcNumber: 'PC-05',
        timestamp: '2024-12-22T12:30:00',
        duration: '1h 45m',
    },
    {
        id: 7,
        userId: 'STD-2024005',
        userName: 'Eko Prasetyo',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=eko',
        action: 'check-in',
        facility: 'Lab Komputer A',
        facilityId: 1,
        pcNumber: 'PC-18',
        timestamp: '2024-12-23T09:30:00',
        duration: null,
    },
    {
        id: 8,
        userId: 'STD-2024001',
        userName: 'Ahmad Rizky',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahmad',
        action: 'check-out',
        facility: 'Sound Lab',
        facilityId: 4,
        pcNumber: null,
        timestamp: '2024-12-21T16:00:00',
        duration: '3h',
    },
];

// User weekly stats for personal analytics
export const userWeeklyStats = {
    totalHours: 12.5,
    sessionsCount: 8,
    favoriteSpot: 'Lab Komputer A - PC-05',
    peakDay: 'Selasa',
    weeklyData: [
        { day: 'Sen', hours: 2.5 },
        { day: 'Sel', hours: 3.5 },
        { day: 'Rab', hours: 1.5 },
        { day: 'Kam', hours: 2.0 },
        { day: 'Jum', hours: 3.0 },
        { day: 'Sab', hours: 0 },
        { day: 'Min', hours: 0 },
    ],
};
